"""add language to posts

Revision ID: 649e7373a8bc
Revises: e0628d65d1b1
Create Date: 2020-06-28 13:32:22.708466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649e7373a8bc'
down_revision = 'e0628d65d1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
