"""Account and AccountType

Revision ID: e4eea91e5b41
Revises: d453730527bb
Create Date: 2020-08-14 00:54:56.596346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4eea91e5b41'
down_revision = 'd453730527bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_type_name'), 'account_type', ['name'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('account_type', sa.String(length=128), nullable=True),
    sa.Column('financial_institution', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('opening_balance', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['account_type'], ['account_type.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_account_type_name'), table_name='account_type')
    op.drop_table('account_type')
    # ### end Alembic commands ###
